<div id="<?= $this->name ?>" class="<?= $this->name ?>" style="width: <?= $this->width ?>px; height: <?= $this->height ?>px;">
</div>
<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?sensor=false">
</script>
<script type="text/javascript">
  function initialize<?= $this->name ?>() {
    var latlng = new google.maps.LatLng(<?= $this->centerLatLng ?>);
    var mapOptions = {
      zoom: <?= $this->zoom ?>,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.<?= strtoupper($this->type) ?>,
	  navigationControl: true,
	  scaleControl: true,
	  scrollwheel: <?= ($this->scrollwheel == 'false')?'false':'true' ?>,
	  draggable: <?= ($this->draggable == 'false')?'false':'true' ?>,
	  navigationControl: <?= ($this->navigationControl == 'false')?'false':'true' ?>,
      mapTypeControl: <?= ($this->mapTypeControl == 'false')?'false':'true' ?>,
      scaleControl: <?= ($this->scaleControl == 'false')?'false':'true' ?>,
    };
    var <?= $this->name ?> = new google.maps.Map(document.getElementById("<?= $this->name ?>"), mapOptions);
	
	<?php if ($this->markers): ?>
	<?php foreach($this->markers as $i => $marker): ?>
	  <?php $markerName = $this->name.'_marker'.($i+1); ?>
      var <?= $markerName ?> = new google.maps.Marker({
		position: new google.maps.LatLng(<?= $marker['lat'].", ".$marker['lon'] ?>), 
		map: <?= $this->name ?>,
		title: '<?= $marker['title'] ?>'
	  });
	  if (typeof(MKMapKit) == "object") {
		   MKMapKit.onMarkerCreate(<?= $this->name ?>,<?= $markerName ?>, '<?= $markerName ?>');
	  }
	  google.maps.event.addListener(<?= $markerName ?>, 'click', function() {
	     if (typeof(MKMapKit) == "object") {
			MKMapKit.onMarkerClick(<?= $this->name ?>, <?= $markerName ?>, '<?= $markerName ?>');
		 }
	  });

	<?php endforeach; ?>
	<?php endif; ?>
	if (typeof(MKMapKit) == "object") {
		MKMapKit.initialize(<?= $this->name ?>, '<?= $this->name ?>');
	}
  }
  $(document).ready(function() {
	initialize<?= $this->name ?>();
  });
</script>
